### ISSUE TITLE
Ideas for things to add.

### ISSUE THREAD

**Issue by bryanbraun** [HollyAdele/awesome-programming-for-kids#1]
Swift Playground (for teaching swift)? - http://www.macworld.com/article/3095824/ios/meet-swift-playgrounds-the-learn-to-code-ipad-app-that-feels-like-a-puzzle-game.html

Scratch (a programming language by MIT). Maybe for ages 7-10, or so? https://scratch.mit.edu/

Also, maybe add some kid-friendly resources for minecraft modding? One example is: http://www.learntomod.com/

**Comment by HollyAdele** [comment]
Thanks!  These look awesome.  I added them.
