### ISSUE TITLE
Add "Secret Coders"?

### ISSUE THREAD

**Issue by bryanbraun** [HollyAdele/awesome-programming-for-kids#12]
[Secret Coders](http://www.secret-coders.com/) is a fiction book series that teaches kids Logo.

Maybe also consider the "[Code Master](https://www.thinkfun.com/products/code-master/)" board game.

And maybe [Cubetto](https://www.primotoys.com/)

And maybe "[Code-a-Pillar](https://www.target.com/p/fisher-price-think-learn-code-a-pillar/-/A-50720193)" and "[Bee-Bot](https://www.amazon.com/Bee-Bot-R-Rechargeable-Robot/dp/B0141I3RBU)" (though that last one might not be programming-centric enough).

**Comment by HollyAdele** [comment]
I'm going to add Secret Coders and Code Master because they are comprehensive and not expensive. 

However, I am not going to add Cubetto, Code-a-Pillar, or Bee-Bot, although they look like a lot of fun. They are more expensive than I would like, and they teach fewer concepts than I would like.
